- id: '1679575010017'
  alias: Low battery warning
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition:
  - condition: template
    value_template: '{% set threshold = 50 %} {{ expand("group.batteries") |  map(attribute=''state'')
      | map(''int'') | select(''<='', threshold) | list | count > 0 }}'
  action:
  - service: notify.notify
    data:
      message: "{% set ns = namespace(low=[]) %}   {% set threshold = 50 %}  {%- for
        sensor in expand(\"group.batteries\") -%}\n  {%- if int(sensor.state) <= threshold
        -%}\n    {%- set ns.low = ns.low + [ sensor.name[:-6] ~ ' (' ~ sensor.state
        | int ~ '%)'] %}\n  {%- endif -%} {%- endfor -%} \n{{ ns.low | join(\", \")
        }}"
      title: Low battery warning
  - service: notify.persistent_notification
    data:
      message: "{% set ns = namespace(low=[]) %}   {% set threshold = 50 %}  {%- for
        sensor in expand(\"group.batteries\") -%}\n  {%- if int(sensor.state) <= threshold
        -%}\n    {%- set ns.low = ns.low + [ sensor.name[:-6] ~ ' (' ~ sensor.state
        | int ~ '%)'] %}\n  {%- endif -%} {%- endfor -%} \n{{ ns.low | join(\", \")
        }}"
      title: Low battery warning
  mode: single
- id: '1679926615102'
  alias: Greenhouse temperature warning
  description: Too hot or too cold
  trigger:
  - platform: numeric_state
    entity_id: sensor.greenhouse_temperature
    above: 32
  - platform: numeric_state
    entity_id: sensor.greenhouse_temperature
    below: 5
  condition: []
  action:
  - service: notify.notify
    data:
      message: 'Greenhouse temperature: {{ states(''sensor.greenhouse_temperature'')
        | round(1) }} °C'
      title: Greenhouse temperature warning
  - service: notify.persistent_notification
    data:
      message: 'Greenhouse temperature: {{ states(''sensor.greenhouse_temperature'')
        | round(1) }} °C'
      title: Greenhouse temperature warning
  mode: single
- id: '1680012121042'
  alias: Stale sensor
  description: ''
  trigger:
  - platform: webhook
    webhook_id: -RwuPrAoOVcVGTQ505Aq_uPdA
  condition: []
  action:
  - service: notify.notify
    data:
      title: Stale sensor warning
      message: '{{ trigger.data["sensor"] }} not seen for {{ trigger.data["last_changed"]
        }} hour(s)'
  - service: persistent_notification.create
    data:
      title: Stale sensor warning
      message: '{{ trigger.data["sensor"] }} not seen for {{ trigger.data["last_changed"]
        }} hour(s)'
  mode: single
- id: '1583793635215'
  alias: Pip's heating on
  description: Make sure Pip's room never less than 16C
  trigger:
  - at: '18:30:00'
    platform: time
  condition: []
  action:
  - service: climate.set_temperature
    data:
      temperature: 16
    target:
      entity_id:
      - climate.pip_s_room
  - service: climate.set_hvac_mode
    data:
      hvac_mode: heat
    target:
      entity_id: climate.pip_s_room_electric
  mode: single
- id: '1583793687978'
  alias: Pip's heating off
  description: Make sure Pip's room never less than 16C
  trigger:
  - at: 06:00:00
    platform: time
  condition: []
  action:
  - service: climate.set_hvac_mode
    data:
      hvac_mode: 'off'
    target:
      entity_id: climate.pip_s_room_electric
  mode: single
- id: '1585479851181'
  alias: Attic Heating On
  description: Monday - Thursday
  trigger:
  - at: 08:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
  action:
  - type: turn_on
    device_id: 761ef68fa54a4a7881f7be9a21a8f431
    entity_id: switch.attic_boiler
    domain: switch
  - service: homeassistant.turn_on
    target:
      entity_id: group.attic_heating
  mode: single
- id: '1585479910387'
  alias: Attic Heating Off (MTWT)
  description: ''
  trigger:
  - at: '17:15'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
  action:
  - service: homeassistant.turn_off
    target:
      entity_id: group.attic_heating
  - type: turn_off
    device_id: 761ef68fa54a4a7881f7be9a21a8f431
    entity_id: switch.attic_boiler
    domain: switch
  mode: single
- id: '1589031338739'
  alias: Oil Boiler On (Morning)
  description: ''
  trigger:
  - platform: time
    at: 05:30:00
  condition: []
  action:
  - data: {}
    entity_id: climate.central_heating
    service: climate.turn_on
  - type: turn_off
    device_id: c639fbc404b04062a0623a6366b1d147
    entity_id: switch.seed_mat
    domain: switch
  mode: single
- id: '1589031374264'
  alias: Oil Boiler Off
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  - at: '21:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: climate.central_heating
    service: climate.turn_off
  - delay:
      hours: 1
      minutes: 0
      seconds: 0
      milliseconds: 0
  - type: turn_on
    device_id: c639fbc404b04062a0623a6366b1d147
    entity_id: switch.seed_mat
    domain: switch
    enabled: false
  mode: single
- id: '1593616611856'
  alias: Towel Radiators On
  description: Switch on twice a day
  trigger:
  - at: '6:30:00'
    platform: time
  - platform: time
    at: '18:30:00'
  condition: []
  action:
  - type: turn_on
    device_id: cf9a6fd56a6e479083dd8a009009d843
    entity_id: switch.shower_towel_radiator
    domain: switch
  - type: turn_on
    device_id: 4bc7db6c1e3ea691424de81704d011b1
    entity_id: switch.bathroom_towel_radiator
    domain: switch
  mode: single
- id: '1595402424113'
  alias: Hot Water Bath On
  description: Set to 55C for bath between 5.30pm and 8.00pm
  trigger:
  - at: '17:00:00'
    platform: time
  condition: []
  action:
  - data:
      temperature: 55
    service: climate.set_temperature
    target:
      entity_id: climate.hot_water_immersion
  - data: {}
    entity_id: climate.hot_water_immersion
    service: climate.turn_on
  mode: single
- id: '1600861399230'
  alias: Tower Radiators Off
  description: Leave on for 2 hours a day
  trigger:
  - at: 08:30:00
    platform: time
  - platform: time
    at: '20:30:00'
  condition: []
  action:
  - type: turn_off
    device_id: cf9a6fd56a6e479083dd8a009009d843
    entity_id: switch.shower_towel_radiator
    domain: switch
  - type: turn_off
    device_id: 4bc7db6c1e3ea691424de81704d011b1
    entity_id: switch.bathroom_towel_radiator
    domain: switch
  mode: single
- id: '1600861508332'
  alias: Hot Water Bath Off
  description: Kids
  trigger:
  - at: '20:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: climate.hot_water_immersion
    service: climate.turn_off
  mode: single
- id: '1602964318533'
  alias: Kitchen Heating On
  description: AirBnB
  trigger:
  - at: 07:00
    platform: time
  - at: '17:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: climate.kitchen
    service: climate.turn_on
  mode: single
- id: '1602964390042'
  alias: Kitchen Heating Off
  description: ''
  trigger:
  - at: 09:00
    platform: time
  - at: '20:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: climate.kitchen
    service: climate.turn_off
  mode: single
- id: '1616575764487'
  alias: Oil Boiler On (Evening)
  description: ''
  trigger:
  - at: '17:00:00'
    platform: time
  condition: []
  action:
  - data: {}
    entity_id: climate.central_heating
    service: climate.turn_on
  - type: turn_off
    device_id: c639fbc404b04062a0623a6366b1d147
    entity_id: switch.seed_mat
    domain: switch
  mode: single
- id: '1634585277038'
  alias: Tackroom & Laundry Heating On
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - type: turn_on
    device_id: 088c4fdcc84073321935c6a00f821fbb
    entity_id: switch.tackroom_heater
    domain: switch
  - type: turn_on
    device_id: ce44b52ec54be73a6721b3e01bbdc677
    entity_id: switch.laundry_heater
    domain: switch
  mode: single
- id: '1634585304967'
  alias: Tackroom & Laundry Heating Off
  description: ''
  trigger:
  - platform: time
    at: 02:00
  condition: []
  action:
  - type: turn_off
    device_id: 088c4fdcc84073321935c6a00f821fbb
    entity_id: switch.tackroom_heater
    domain: switch
  - type: turn_off
    device_id: ce44b52ec54be73a6721b3e01bbdc677
    entity_id: switch.laundry_heater
    domain: switch
  mode: single
- id: '1636110238201'
  alias: Attic Visitors Weekend on
  description: ''
  trigger:
  - platform: time
    at: '18:00:00'
  - platform: time
    at: 05:00:00
  condition: []
  action:
  - type: turn_on
    device_id: 761ef68fa54a4a7881f7be9a21a8f431
    entity_id: switch.attic_boiler
    domain: switch
  - type: turn_on
    device_id: 761ef68fa54a4a7881f7be9a21a8f431
    entity_id: switch.attic_radiators
    domain: switch
  mode: single
- id: '1636110308988'
  alias: Attic Visitors Weekend off
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - type: turn_off
    device_id: 761ef68fa54a4a7881f7be9a21a8f431
    entity_id: switch.attic_radiators
    domain: switch
  - type: turn_off
    device_id: 761ef68fa54a4a7881f7be9a21a8f431
    entity_id: switch.attic_boiler
    domain: switch
  mode: single
- id: '1676556187794'
  alias: Grow light on
  description: ''
  trigger:
  - platform: sun
    event: sunrise
    offset: 0
  condition: []
  action:
  - type: turn_on
    device_id: 9b047ec8e83543bcb2e76130a25f0abe
    entity_id: switch.grow_light
    domain: switch
  mode: single
- id: '1676556207273'
  alias: Grow light off
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - type: turn_off
    device_id: 9b047ec8e83543bcb2e76130a25f0abe
    entity_id: switch.grow_light
    domain: switch
  mode: single
- id: '1683129319083'
  alias: Daily backup
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: backup.create
    data: {}
  mode: single
- id: '1683229922981'
  alias: Garden Cottage next day Hot Water on
  description: Turn on hot water in time for 2pm check in
  trigger:
  - platform: time
    at: '12:00:00'
  condition: []
  action:
  - type: turn_on
    device_id: 8cff03562b97767a1fe912fc7a4feb7d
    entity_id: switch.gc_hot_water_immersion
    domain: switch
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.garden_cottage_next_day_hot_water
  mode: single
- id: '1683230239239'
  alias: Garden Cottage next day Hot Water off
  description: Turn off hot water at 11am checkout
  trigger:
  - platform: time
    at: '11:00:00'
  condition: []
  action:
  - type: turn_off
    device_id: 8cff03562b97767a1fe912fc7a4feb7d
    entity_id: switch.gc_hot_water_immersion
    domain: switch
  - service: automation.turn_off
    data: {}
    target:
      entity_id: automation.garden_cottage_next_day_hot_water_off
  mode: single
