
# Loads default set of integrations. Do not remove.
default_config:

# Temporary use of a different port to allow migration from live
# HA instance, which is running on port 8123

http:
  server_port: 8124

influxdb:
  api_version: 2
  ssl: false
  host: localhost
  port: 8086
  token: !secret influxdb_token
  organization: df0111dc4de9d828
  bucket: homeassistant 
  exclude:
    domains:
      - media_player
      - persistent_notification
      - sun
      - weather
      - zone
                

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
mqtt:
  sensor: !include sensor-mqtt.yaml
sensor: !include sensor.yaml